# build environment
FROM node:15.3.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.0 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY docker-entrypoint.sh generate_config.sh /
RUN chmod +x docker-entrypoint.sh generate_config.sh

EXPOSE 80
ENTRYPOINT [ "/docker-entrypoint.sh" ]
