version: "3.3"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      TOKEN: ${BOT_TOKEN}
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    volumes:
      - "./bot/files:/files"
    ports:
      - "9080:9080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME}
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DISCORD_CLIENT_ID: ${CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      API_HOSTNAME: ${API_HOSTNAME}
      SITE_HOSTNAME: ${SITE_HOSTNAME}
      SECRET_KEY: ${SECRET_KEY}
      REDIRECT_URL: ${REDIRECT_URL}
    volumes:
      - "./backend:/app"
    ports:
      - "8800:80"
    depends_on:
      - redis
      - db
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-worker
    volumes:
      - "./backend:/app"
    depends_on:
      - redis
      - backend

  redis:
    image: redis:alpine

  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - "./data/party-finder/mysql:/var/lib/mysql"
