version: "3.3"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      TOKEN: ${BOT_TOKEN}
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    volumes:
      - "./bot/files:/files"
    ports:
      - "9080:9080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
      - "./frontend/app/node_modules:/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      API_HOSTNAME: ${API_HOSTNAME}
      SITE_HOSTNAME: ${SITE_HOSTNAME}
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DISCORD_CLIENT_ID: ${CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      API_HOSTNAME: ${API_HOSTNAME}
      SITE_HOSTNAME: ${SITE_HOSTNAME}
      FLASK_SECRET: ${FLASK_SECRET}
      WEBHOOK_ID: ${WEBHOOK_ID}
    volumes:
      - "./backend:/app"
    ports:
      - "8800:5000"
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - "./data/party-finder/mysql:/var/lib/mysql"