version: "3.3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
    volumes:
      - 'frontend:/app'
      - 'frontend/app/node_modules:/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    environment:
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    volumes:
      - "backend:/app"
    ports:
      - "8800:5000"
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - "data/party-finder/mysql:/var/lib/mysql"