version: "3.3"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      TOKEN: ${BOT_TOKEN}
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    volumes:
      - "./bot/files:/files"
    ports:
      - "9080:9080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
      API_HOSTNAME: ${API_HOSTNAME}
      SITE_HOSTNAME: ${SITE_HOSTNAME}
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME}
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DISCORD_CLIENT_ID: ${CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      API_HOSTNAME: ${API_HOSTNAME}
      SITE_HOSTNAME: ${SITE_HOSTNAME}
      SECRET_KEY: ${SECRET_KEY}
      WEBHOOK_ID: ${WEBHOOK_ID}
      SUPERUSERS: ${SUPERUSERS}
    volumes:
      - "./backend:/app"
    ports:
      - "8800:80"
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      SUPERUSERS: ${SUPERUSERS}
    volumes:
      - "./data/party-finder/mysql:/var/lib/mysql"