version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    volumes:
      - './frontend:/app'
      - './frontend/app/node_modules:/app/node_modules'
    ports:
      - "3001:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      DB_NAME: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    volumes:
      - "./backend:/app"
    ports:
      - "8800:80"
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - "/srv/docker/data/party-finder/mysql:/var/lib/mysql"
