FROM python:3.8-slim-buster

WORKDIR /app

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "worker", "--app=worker.app", "--loglevel=info"]