"""Party locking

Revision ID: 5055fc3e627c
Revises: a5f6248d29fe
Create Date: 2021-07-27 08:10:56.142443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5055fc3e627c"
down_revision = "a5f6248d29fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parties", sa.Column("locked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parties", "locked")
    # ### end Alembic commands ###
